version: 2
jobs:
  test:
    docker:
      - image: cirrusci/flutter:latest
    steps:
      - checkout
      - run:
          command: flutter test
  build:
    docker:
      - image: cirrusci/flutter:latest
    steps:
      - checkout
      - run:
          command: flutter build apk
  release:
    docker:
      - image: cirrusci/flutter:latest
    steps:
      - checkout
      - run:
          name: Release
          command: |
            flutter test
            flutter build apk --release
      - store_artifacts:
          path: build/app/outputs/apk/app.apk
          destination: android_app
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
  test_and_release:
    jobs:
      - release:
          filters:
            tags:
              only: /^v.*/
